### ISSUE TITLE
Usage & saving behaviour -  Comments 

### ISSUE THREAD

**Issue by TiddlyTweeter** [TiddlyWiki/TiddlyFox#52]
In some of the discussion on Google Groups it became clear to me that quite a few people who have upgraded to the later version were unclear you have to actively enable saving. This seems to be affecting old users more than new ones. 

Q1 - Why is the DEFAULT no longer to save?

Q2 - Would it be doable to have an alert message that the first time a users opens a TW it, essentially, points out how the new TF works?

ON ICONS. I note that the new icons are clearer. But I think lots of folk were not paying attention to any icons as they were accustomed to transparent saving so maybe it won't entirely solve the issue? BTW, personally I would have preferred something thematically cat. Like a cat's face in different colours. If you go round this again I could probably design them for you if relevant.

Best wishes
Josiah

**Comment by Jermolene** [comment]
The first thing to emphasise is that the only reason I had to rewrite TiddlyFox from scratch was because Mozilla decided to change the way that Firefox works by deprecating the old extension APIs. I had to learn how to use a whole new SDK to write v2.x, and then not long afterwards I learned that Mozilla was going to disable that API, too. So, from my point of view, working on TiddlyFox is an absolute pain in the neck, made more difficult by Mozilla's terrible documentation and endless strategic chopping and changing.

> Q1 - Why is the DEFAULT no longer to save?

The default has never been to enable saving. v1.x prompted the user via an alert and v2.x (currently) prompts the user via the toolbar button icon.

We need user interaction before enabling saving to prevent abuse. How embarrassing would it be if somebody wrote a virus that targeted tens of thousands of active users of TiddlyFox?

> Q2 - Would it be doable to have an alert message that the first time a users opens a TW it, essentially, points out how the new TF works?

v1.x used a modal JavaScript alert to warn the user. Extensions using the newer API in v2.x are not able to create modal alerts, as far as I can tell.

**Comment by Jermolene** [comment]
> ON ICONS. I note that the new icons are clearer. But I think lots of folk were not paying attention to any icons as they were accustomed to transparent saving so maybe it won't entirely solve the issue?

I agree that colouring the icon is an inadequate way of alerting the user. However I haven't been able to discover how to do it a better way with the available APIs. That's why we are reduced to improving the icon design.

> BTW, personally I would have preferred something thematically cat. Like a cat's face in different colours. If you go round this again I could probably design them for you if relevant.

I'm happy to review submissions. It's quite a challenge; the toolbar icon has to work at both 16x16 and 32x32 pixels.

**Comment by TiddlyTweeter** [comment]
Its maybe too easy to forget you are neither omniscient, nor much better able to cope with the folly of future web browser history than the rest of us.

I'll look at the cat icon idea. If it looks doable I'll let you know.

**Comment by Jermolene** [comment]
Thanks @TiddlyTweeter much appreciated.

**Comment by Jermolene** [comment]
Hi @TiddlyTweeter please see #53.

Can this issue be closed?
